// demos/react/src/App.tsx
import { useRef, useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import type { SearchModalSnippet } from "@cloudflare/ai-search-snippet";

function App() {
  const [count, setCount] = useState(0);

  const searchModalRef = useRef<SearchModalSnippet>(null);

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank" rel="noopener">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noopener">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)} type="button">
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      <search-bar-snippet apiUrl="http://localhost:8787" />
      <br />

      <button
        onClick={() => {
          searchModalRef.current?.open();
        }}
        type="button"
      >
        Show Modal Search (CMD+K)
      </button>

      <search-modal-snippet
        apiUrl="http://localhost:8787"
        ref={searchModalRef}
      />
    </>
  );
}

export default App;

// apps/demo-vue/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue';
import '@cloudflare/ai-search-snippet';
import { useTemplateRef } from 'vue';

const modalSearch = useTemplateRef('modalSearch');
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
  <search-bar-snippet apiUrl="http://localhost:8787" />
  <br />
  <button @click="modalSearch.open()">Show Modal Search (CMD+K)</button>

  <search-modal-snippet apiUrl="http://localhost:8787" ref="modalSearch" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
